### ISSUE TITLE
     Failed! MPesa Error 404.001.03: Invalid Access Token

### ISSUE THREAD

**Issue by josmbolomnyoi** [osenco/osen-wc-mpesa#10]
I am having difficulty on this any help....any help please

**Comment by maukoese** [comment]
Check your credentials. Make sure they are all correct. The App Consumer Key, The Consumer Secret are what are used to generate the access token. So make sure those are correct.

**Comment by maukoese** [comment]
Yes. In the admin settings - make sure the credentials you are using there are correct. Kindly do not use the ones provided in the plugin. Create your own.

**Comment by josmbolomnyoi** [comment]
i am changing the Online Pass Key on the admin side

**Comment by maukoese** [comment]
The online passkey has noting to do with it. It's the consumer secret ans consumer key that need to be changed.

**Comment by maukoese** [comment]
The online passkey has noting to do with it. It's the consumer secret ans consumer key that need to be changed.

**Comment by josmbolomnyoi** [comment]
Have tried its been giving me this since dawn to generate token using my Consumer Key and secrete but below is what i'm getting as response so frustrating
--




HTTP/1.1 200 OK
Age:
44922
Connection:
keep-alive
Content-Encoding:
gzip
Content-Length:
856
Content-Type:
text/html
Date:
Thu, 04 Oct 2018 08:37:06 GMT
Last-Modified:
Fri, 07 Sep 2018 19:43:09 GMT
Server:
Apigee SPA Proxy
Set-Cookie:
access_token=;Path=/;Expires=Thu
Strict-Transport-Security:
max-age=31536000
Vary:
Accept-Encoding
Via:
1.1 780c40460121bc788be5e09e5483f7dd.cloudfront.net (CloudFront)
X-Amz-Cf-Id:
BHQnexv1KZ789hqJMeu_gzd9korAjpE3jlvasrZqN_HnnRb0oyBmug==
X-Cache:
Hit from cloudfront
X-Frame-Options:
DENY
<!doctype html>
<html>
<head>
    <title>Apigee</title>
    <link rel="shortcut icon" type="image/x-icon" href="/static-assets/favicon.ico" sizes="64x64">
    <link rel="preload" href="/static/v2.1.0/apigee.css" as="style">
    <link rel="stylesheet" href="/static-assets/static.css?v=1.3.1">
    <script>
        dataLayer = [{'webapp.name': 'static'}];
    </script>
</head>
<body>
    
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-N52333" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-N52333');
    </script>
    

    <main class="app-view">
        <article class="static-content">
            <div class="apigee-logo"></div>
            <div class="static-content-title">Error: 404</div>
            <div class="static-content-text">
                Sorry, the page you're looking for can't be found. <br/> Try checking the URL for errors? <br/> Keep getting this page? Report this to our support team.
            </div>

            <button class="alm-button-action-filled" onclick="location.href='/'">Go to home page</button>
        </article>
    </main>
</body>
</html>

**Comment by maukoese** [comment]
Give me a call on +254204404993 because this is an issue no one else has faced before. The plugin is rather straightforward.

**Comment by josmbolomnyoi** [comment]
Failed! MPesa Error 404.001.03: Invalid Access Token


i have use my consumer key and consumer secrete then used test online shortcode and still getting the error

**Comment by maukoese** [comment]
Hey. Did you ever get this resolved?

**Comment by rmutili** [comment]
I can't get the plugin installed.. Its crushing my site. Any assistance?

**Comment by maukoese** [comment]
Kindly open your own issue for this.

**Comment by maukoese** [comment]
What shortcodes are you using?

**Comment by maisondudigital** [comment]
Hi, I have the exact same issue. Even though my Key and secret are correct.

**Comment by stevenjuguna93** [comment]
Greetings, I am receiving Failed! MPesa Error 404.001.03: Invalid Access Token, even though my key and secret are correct.

**Comment by maukoese** [comment]
1. Make sure you’ve set the correct environment 

2. If you are on sandbox mode, you cannot use live credentials. Similarly, if you are on live mode, you have to use a production app’s credentials, not a sandbox app.

**Comment by Dismod** [comment]
Failed! MPesa Error 404.001.03: Invalid Access Token
 I am also getting the same error

**Comment by maukoese** [comment]
Check your configuration, make sure you’re using the correct credentials.

**Comment by sulley-maker** [comment]
**I'm getting this error**
Failed! MPesa Error 400.002.02: Bad Request - Invalid CallBackURL

**Comment by maukoese** [comment]
Which version are you using? Please make sure you are using the latest one.

**Comment by sulley-maker** [comment]
I'm using the latest version 1.20.99

**Comment by maukoese** [comment]
Please, next time open your own issue, instead of commenting on an old issue which is already closed.

**Comment by maukoese** [comment]
What is the url of your website? Or rather, which website are you using the plugin on?

**Comment by sulley-maker** [comment]
I'm using wordpress to create a WooCommerce
Localhost xampp

**Comment by maukoese** [comment]
That's the problem. You can't use localhost. The localhost in the url is what is making the callback URL invalid. 

My suggestion would be to either use virtual hosts, or upload to an actual domain.

**Comment by sulley-maker** [comment]
Ow
Alright
Thank you so much

I'm using local host just for the development but when I'm done with it
I'll buy a domain

Thank you sir

**Comment by maukoese** [comment]
See this link on how to use virtual hosts. It helps with pretty URLs and stuff

https://www.cloudways.com/blog/configure-virtual-host-on-windows-10-for-wordpress/

**Comment by sulley-maker** [comment]
Thank you

**Comment by sulley-maker** [comment]
Hey osenco
Thank you for the plugin
It works perfectly
I wanted to ask you about sandbox and live
I'm getting a "Safaricom-test 12"
I want the STK Push to show my organisation's name on the phone

Can you help me with that?

**Comment by maukoese** [comment]
If you are on sandbox it cannot show your organization name. I can assit with going live for KSh 4000. Hit me up on 0705459494 for more.

**Comment by tonitechwiz** [comment]
im getting this error what could be the issue
Failed! MPesa Error 404.001.03: Invalid Access Token

**Comment by maukoese** [comment]
Please read the conversation in this issue before commenting. Thanks.

**Comment by tonitechwiz** [comment]
STK push was working before but now I tried again I'm getting this message 
****"STK Push didn't work? Pay Manually Via M-PESA"****

**Comment by paulkiragu621** [comment]
> I'm getting this error what could be the issue Failed! MPesa Error 404.001.03: Invalid Access Token

Kindly open a new app then ensure you tick the fields below, otherwise, it won't work on sandbox:

1. Lipa Na Mpesa Sandbox

2.MPesa Sandbox

This worked for me! Don't pay this person asking for me on an open-source platform

**Comment by Baldwinsure** [comment]
Hello 
am getting this error (MPesa Error) 404.001.03: Invalid Access Token. Despite having the consumer key and secret and they are correct in addition the site is on a live domain and the environment is live and the credentials am using are also of a live app which has been approved  please help

**Comment by MuokaPWambua** [comment]
I had the same problem, the problem was that I was using the whole json response when generating the access key 
`access_token =  {
  "access_token": "dGfvhkcJo5rPcEg2vU",
  "expires_in": "3599"
}` 
instead of using the access_token itself, something like this `  access_token = response['access_token']`

**Comment by maukoese** [comment]
The issue is not with the code. Cause the plugin is working on hundreds of websites ,

The problem comes up when you use the wrong consumer key/secret, probably because you did not copy all of it or there's space; or forgeting to set the correct environment i.e Production when you are using sandbox credentials or vice versa.

**Comment by Arlus** [comment]
I contacted Mpesa API support and they solved the issue for me with an action on their end.

**Comment by maukoese** [comment]
Awesome!

**Comment by brianmak3** [comment]
![Screenshot 2024-09-06 at 20 47 26](https://github.com/user-attachments/assets/08468c8b-4dec-4aed-a8db-64ea0a069106)
Am getting this same error despite doing the correct configuration and using the correct environment. To be sure, I have another app which I only changed the secret, key and pass_key and it worked fine. But on the new app I registered it does not work.

**Comment by brianmak3** [comment]
I got my issue sorted from the APIs support team. Sometimes the issue is not your configuration but from their side.

**Comment by samzillah** [comment]
Am still getting the same error and i have the corrrect credentials . when using till My client got a Till No, Store No & shortcode. So which should appear where

**Comment by brianmak3** [comment]
You need to reach out the APIs support team through the email apisupport@safaricom.co.ke and describe for them your issue. That is how I solved my same case.

**Comment by samzillah** [comment]
so what did they say the issue was

**Comment by Arlus** [comment]
@samzillah they won't say. Just reach out and ask them to solve it.

**Comment by brianmak3** [comment]
They will just solve it for you, they won't say what the issue was.

**Comment by samzillah** [comment]
when using till No. 
I have Till No, Store No & Shortcode 
On the plugin , there is store number and Business shortcode,
Which Should go where ? The tooltip in Shortcode is saying i add Till . Whats Up

**Comment by wamae-ndiritu** [comment]
I had the same issue and had to contact [apisupport@safaricom.co.ke](mailto:apisupport@safaricom.co.ke) for help. The problem was fixed within no time!

**Comment by Fordyboy124** [comment]
For those who solved the issue kindly share how you did it

**Comment by wamae-ndiritu** [comment]
> For those who solved the issue kindly share how you did it

try contacting API support. Sometimes the issue is on their end

**Comment by Fordyboy124** [comment]
i contacted the api support and they solved immediately, the problem was on there end

**Comment by kaberaarthur** [comment]
I Hate Safaricom
