### ISSUE TITLE
Pluggin crashes site on installation

### ISSUE THREAD

**Issue by rmutili** [osenco/osen-wc-mpesa#12]
I can't get the plugin installed.. Its crushing my site. Any assistance will be highly appreciated...

**Comment by kevinkavai** [comment]
Did you download the plugin from the site or from GitHub?

**Comment by rmutili** [comment]
I tried both from site and git hub... It installs but when I try to activate, sit crashes. 

Sent from Yahoo Mail on Android 
 
  On Sat, 19 Jan 2019 at 7:01 p.m., Kevin Kavai<notifications@github.com> wrote:   Did you download the plugin from the site or from GitHub?

**Comment by Evanskim** [comment]
Disable it when customizing your site. Especially when you're using flat
some.

**Comment by rmutili** [comment]
Please come again,  I dont get your statement... I didnt even get it working.. Cam you assist with installation?

**Comment by maukoese** [comment]
What version of PHP are you using?

**Comment by rmutili** [comment]
> What version of PHP are you using?

Am using PHP 7.0

**Comment by maukoese** [comment]
What does your error/debug log say?

**Comment by rmutili** [comment]
Am hosting using cpanel, I will need to check on that.

**Comment by rmutili** [comment]
Managed to get it working. Issue was another conflicting plugin. 

**Fatal error: Cannot declare class WC_Gateway_MPESA, because the name is already in use in /home/paulkilu/public_html/wp-content/plugins/osen-wc-mpesa-1.7.13/osen-wc-mpesa.php on line 177**

**Comment by maukoese** [comment]
Alright then.
