### ISSUE TITLE
Version 1.8.8 - Paid Field Is Sometimes Doubled or Tripped

### ISSUE THREAD

**Issue by abdazz25** [osenco/osen-wc-mpesa#21]
Hi @maukoese 
I am using the plugin version 1.8.8 with a Lipa Na Mpesa Till Number. I dont know what happens but sometimes the Paid Field is double or triple the actual amount from the mpesa transaction code. Maybe you can look in to this.

![image](https://user-images.githubusercontent.com/3838823/63406367-56f66100-c3f2-11e9-9955-a58668e87bdd.png)

**Comment by maukoese** [comment]
Kindly update to the latest version, this issue was fixed.

**Comment by abdazz25** [comment]
Okay, well noted. Thanks
