### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by abdazz25** [osenco/osen-wc-mpesa#22]
Hi @maukoese 
Could you check on these errors. 

enable_b2c in /home2/arduinoco/public_html/wp-content/plugins/osen-wc-mpesa-1.19.8/src/Menus/Menu.php on line 19

Notice: Undefined index: enable_b2c in /public_html/wp-content/plugins/osen-wc-mpesa-1.19.8/src/Menus/Menu.php on line 48

Notice: Undefined index: enable_b2c in public_html/wp-content/plugins/osen-wc-mpesa-1.19.8/inc/wc_mpesa_gateway.php on line 49

Also the receipt notification is repeating many times.

![image](https://user-images.githubusercontent.com/3838823/63795337-6b63bd80-c90c-11e9-8e19-c8a6f7970c35.png)

![image](https://user-images.githubusercontent.com/3838823/63795375-7e768d80-c90c-11e9-8aaa-49cb5ed056ed.png)

**Comment by maukoese** [comment]
Working on it. We will have fixed everything in the next release, next week.

**Comment by migoya2020** [comment]
Hi @maukoese 
Thanks for this nice peace. 
i have done a test run on woocommerce but  the process is stuck at "Confirming payment..."  and it doesnt move past that. check this https://ibb.co/S60pLw5
However, i get an email that the  order as done successfully.
Do you  know what could be wrong?

thank you

**Comment by maukoese** [comment]
The duplicates were coming from Daraja, and not the plugin.

**Comment by abdazz25** [comment]
@maukoese you mean daraja has a bud and they need to fix it?

**Comment by abdazz25** [comment]
Hi @maukoese ,
Has this been fix?

enable_b2c in /home2/arduinoco/public_html/wp-content/plugins/osen-wc-mpesa-1.19.8/src/Menus/Menu.php on line 19

Notice: Undefined index: enable_b2c in /public_html/wp-content/plugins/osen-wc-mpesa-1.19.8/src/Menus/Menu.php on line 48

Notice: Undefined index: enable_b2c in public_html/wp-content/plugins/osen-wc-mpesa-1.19.8/inc/wc_mpesa_gateway.php on line 49


Regards,
Abdalla

**Comment by maukoese** [comment]
Yes, this was fixed.
