### ISSUE TITLE
Confirming payment... ERROR

### ISSUE THREAD

**Issue by migoya2020** [osenco/osen-wc-mpesa#23]
Hi @maukoese 
Thanks for this nice piece. 
i have done a test run on woocommerce but  the process is stuck at "Confirming payment..."  and it doesnt move past that. check this https://ibb.co/S60pLw5
However, i get an email that the  order as done successfully.
Do you  know what could be wrong?

thank you

**Comment by maukoese** [comment]
Hi, 
Kindly ensure you have updated your permalinks, and that your site is running over HTTPS. The payment confirmation polls the database until if finds the receipt number sent with the IPN. So, if it doesn't move past that then it means you are not receiving the notification.

The plugin does not complete orders until full payment has been received.

**Comment by migoya2020** [comment]
Hi @maukoese , thanks for your feedback. i already enabled https on my WooCommerce website and the URLs are now in https. however,  i still cant get the Confirmation and Validation URLs thats required in the Daraja API so that i can register them. where do i get the confirmation and Validation URLs? 
thank you.
David.

**Comment by maukoese** [comment]
The plugin handles URL registration. There is a button in the admin that you click and it registers the URLs for you. Check the plugin configuration page.
