### ISSUE TITLE
Error when activating  Plugin

### ISSUE THREAD

**Issue by migoya2020** [osenco/osen-wc-mpesa#26]
I get this error when i activate plugin.
![Screenshot 2019-10-02 10 59 05](https://user-images.githubusercontent.com/23479444/66027575-def87c00-e503-11e9-93ae-e6eb54dec69c.png)

Even though the  plugin gets activated but when i try to register URLS, i get an error as well.
"Could not register M-PESA URLs, try again later."
Whats coursing this error ?
thank you

**Comment by maukoese** [comment]
Hi,
Have you enabled external validation for your shortcode? Also, what version of the plugin are using?

**Comment by migoya2020** [comment]
Hi 
please, excuse my ignorance but where do i activate the external Validation? i have checked inside Daraja App  and the plugin but i cant find this.
am using osen-wc-mpesa-1.19.8 of the plugin.

thank you

**Comment by maukoese** [comment]
You need to email apisupport@safaricom.co.ke and ask them to activate external validation for you.
