### ISSUE TITLE
Connect to daraja

### ISSUE THREAD

**Issue by benmoh1** [osenco/osen-wc-mpesa#29]
I get this error when testing payment on clients side. Failed! MPesa Error 1: Could not connect to Daraja 

![image](https://user-images.githubusercontent.com/39403471/76657607-46225e00-6583-11ea-8248-444700dc510a.png)

**Comment by maukoese** [comment]
This happens when your server can’t communicate with Safaricom Mpesa. 

Make sure you can connect to the internet and your server can send out requests.
