### ISSUE TITLE
Unable to register callback URL

### ISSUE THREAD

**Issue by jkoech** [osenco/osen-wc-mpesa#31]
I'm working on sandbox, I have put everything correctly but I can't register the callback URL. I get the error 'Could not register M-PESA URLs, try again later'.
Is M-PESA developer portal experiencing issues?
I also tried creating a new app but it keeps failing.
![daraja](https://user-images.githubusercontent.com/365745/84436604-6920e480-ac3c-11ea-9042-9c20c1e7414d.JPG)
![osen](https://user-images.githubusercontent.com/365745/84436639-776f0080-ac3c-11ea-8c81-f94bbe4cfa28.JPG)

**Comment by maukoese** [comment]
You cannot register callback URLs in sandbox. And those are not even necessary unless you want offline payments. The plugin will work fine without that.

**Comment by jkoech** [comment]
@maukoese noted. Does STK push work on sandbox?
I tried but I didn't receive the push on my phone.

**Comment by maukoese** [comment]
The STK push work on sandbox, so long as it is configured correctly with the test credentials from Daraja. The plugin does come with test credentials for you you to use in sandbox.

**Comment by jkoech** [comment]
For some reason, I'm not getting the STK push on sandbox with everything configured correctly.
I've tried for 3 days now. Everything else seems to work fine. 
![no-stk](https://user-images.githubusercontent.com/365745/84502964-fce8c400-acc1-11ea-9d61-afc55a3bcf28.png)
