### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by teddiey** [osenco/osen-wc-mpesa#39]
Just encountered this issue for the first time ever, please help

Fatal error: require_once(): Failed opening required '/home/timeless/........../public_html/radio/wp-content/plugins/osen-wc-mpesa-master/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/........./public_html/radio/wp-content/plugins/osen-wc-mpesa-master/osen-wc-mpesa.php on line 50

![mpesaError](https://user-images.githubusercontent.com/16349015/106750006-4febfe80-6638-11eb-94a6-20f7512263fd.JPG)

**Comment by KushX** [comment]
Same.
Doesn't look like the files are complete/correct.

**Comment by maukoese** [comment]
Kindly download fromm the releases and not from the source code.

**Comment by teddiey** [comment]
@maukoese Thanks, your solution worked
