### ISSUE TITLE
STK PUSH WORKING BUT RESPONSE RECEIVED CONTAINS AN ERROR

### ISSUE THREAD

**Issue by ochiengdan** [osenco/osen-wc-mpesa#48]
the following is the response from Mpesa after one inputs pin:
{"Body":{"stkCallback":{"MerchantRequestID":"40617-17188129-1","CheckoutRequestID":"ws_CO_22062021155116737510","ResultCode":"SFC_IC0003","ResultDesc":"The operator does not exist."}}}

**Comment by maukoese** [comment]
1. What version are you using?
2. Are you using a till or paybill number?

**Comment by ochiengdan** [comment]
Thans for the quic response. I am using version v1.20.99 and Till Number

**Comment by maukoese** [comment]
Issue is probably with the configuration. Make sure you are using your store number, and the till number configured correctly

**Comment by ochiengdan** [comment]
is there a difference between the store number, and the till number

**Comment by maukoese** [comment]
Yes, of course.

Hierarchy is Head Office Number then Store Number, then Buy Goods(Till).

You are supposed to go live with the Store Number and configure the plugin with the correct details.

**Comment by ochiengdan** [comment]
Good morning. Actually I realised  the number was Paybill, however STK Push not working now or is it not supposed to work with Paybill?

**Comment by maukoese** [comment]
The plugin works for both.

If you are configuring for a Paybill, use the same value for both store and shortcode in the settings.

**Comment by ochiengdan** [comment]
Thank you
