### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by techruzz** [osenco/osen-wc-mpesa#63]
Hi 

kindly check the compatibility issue with coupon plugins at checkout. I have tested three different ones e.g. WooCommerce Smart Coupon.

**Comment by maukoese** [comment]
What issues/errors are you getting?

**Comment by techruzz** [comment]
When you try to check out the first time with the coupon applied. you get the error below.
"(M-Pesa Error) 500: cURL error 28: Connection timed out after 5000 milliseconds."

When you submit the second time it works perfectly.

**Comment by techruzz** [comment]
First trial errors
(M-Pesa Error) 500: cURL error 28: Connection timed out after 5001 milliseconds.
(M-Pesa Error) 500: cURL error 28: Connection timed out after 5003 milliseconds.

You have to resubmit again after the error for it to work.

**Comment by maukoese** [comment]
Curl error is not exactly an issue with the plugin, but more with your server. It's probably doing too much and it times out when sending out the request.

You could check which other plugins you have that have hooks firing during checkout, and thus overwhelming the system.

**Comment by techruzz** [comment]
Thank you for your response, I'll be checking which plugin is causing the issue. 

Also, do you have a nice CSS styling for the page that comes after the checkout page? If yes how much is it.
.....................................
Order number: 12352
Date: 23/08/2023
Total: KSh100
Payment method: M-PESA
Confirming payment ......

**Comment by techruzz** [comment]
![msedge_dxDCXnARNc](https://github.com/osenco/osen-wc-mpesa/assets/47551207/a7dde1e8-9465-4ae4-9e3c-fb454ea7f8b2)

**Comment by maukoese** [comment]
If you inspect, those elements have css classes, and perhaps even IDs. You can use those to apply styles. I don't have any ready.

**Comment by techruzz** [comment]
Noted. Thank you so much for the plugin. We do appreciate your time and effort.

**Comment by maukoese** [comment]
You're welcome. Any support, monetary or otherwise, is appreciated.

**Comment by techruzz** [comment]
Sure, share your M-Pesa Number and I will be more than happy to support you with something small.

**Comment by maukoese** [comment]
254705459494

**Comment by techruzz** [comment]
Just sent: Russell

**Comment by Njengah** [comment]
I can help with that styling and make it a contribution. Do you have a design ?

**Comment by techruzz** [comment]
Hello Mr. Njengah,

Thank you for your interest in assisting with styling. Here is the design sample
![STK-Push-Design](https://github.com/osenco/osen-wc-mpesa/assets/47551207/4790823e-50d0-4c09-b92f-2d10311c8b71)
, just wanna keep it simple

**Comment by techruzz** [comment]
![STK Push Design-01](https://github.com/osenco/osen-wc-mpesa/assets/47551207/e940ab08-4716-491d-b4b9-4d10384a11c0)

![STK Push Design-02](https://github.com/osenco/osen-wc-mpesa/assets/47551207/996ec298-3d9a-4fbc-bf92-920b68ce739c)

**Comment by techruzz** [comment]
![STK Push Design-01](https://github.com/osenco/osen-wc-mpesa/assets/47551207/4d845fe1-d555-41b8-9a90-7c8b5ae76b16)

![STK Push Design-02](https://github.com/osenco/osen-wc-mpesa/assets/47551207/6ec13254-25f5-4f08-b783-a20dc045e126)
