### ISSUE TITLE
 cURL error 28: Failed to connect to api.safaricom.co.ke port 443 after 10001 ms: Timeout was reached.

### ISSUE THREAD

**Issue by m-langat** [osenco/osen-wc-mpesa#64]
I am getting this error lately. Tried increasing timeout but not getting through.

**Comment by KIDUCHI** [comment]
Looks like you are doing this on postman?

**Comment by m-langat** [comment]
Not postman. It's the production server. I enabled debug mode

Sincerely,

Michael Lang'at
*Tel: *0724754563

**Comment by m-langat** [comment]
Turns out the error was on Safaricom's side. Couldn't understand why the requests were timed out until I pinged the Safaricom URL from the production server.
