### ISSUE TITLE
Auto currency conversion 

### ISSUE THREAD

**Issue by btbatson** [osenco/osen-wc-mpesa#9]
How do you enable this on the code? i mean when you have a store which sells good on USD how do you auto convert the amount to KES?

**Comment by maukoese** [comment]
I didn’t actually think of that, but if you can provide me an API that does the conversion, I should be able to plug it in for you.

**Comment by btbatson** [comment]
Awesome! am thinking of an Open Source API like https://openexchangerates.org/ but anyway let me find out more about this then let you know. Thanks mate!

**Comment by maukoese** [comment]
Alright. I’ll write something then send it to you.
